### PR TITLE
BSP trees merge request

### PR DESCRIPTION
**Pull request by carnovalejf**
This is a pull request made to the master branch for the weekly report

### CODE REVIEW

**Comment by kevin-kruusi** [comment]
Looks like there are some conflicts you'll need to resolve.
Also you want to avoid pushing the .db files to github.

**Comment by kevin-kruusi** [comment]
Do the reverse first to see these locally, merge master into your BSPTrees branch.

**Comment by k-kruusi** [comment]
Essentially your comment here should explain the purpose of your work, your solution and any steps needed to test it.  Leave the blackboard submission for stuff like weekly report; in the case you did more than 1 ticket it will make more contextual sense.

**Comment by carnovalejf** [comment]
ok ill do that ill merge in master locally then ill remake a new pull request

**Pull request closed without merging**
