### PR TITLE
Create Understanding the Engine.txt

### PR DESCRIPTION
**Pull request by uyu34**
Please refer to the text document that I have made so that it is easier for us to understand how the engine works. This will likely be added to as more code is implemented into the project.

### CODE REVIEW

**Comment by kevin-kruusi** [comment]
Nice job, many projects have to keep their documentation up to date in order to onboard new members.

**Comment by k-kruusi** [comment]
👍

**Comment by uyu34** [comment]
Okay thanks, I'll keep that in mind going forward.

**Comment by JaymieX** [comment]
Oh btw we had a auto generated wiki: https://alteracvalleyhumber2019.github.io/CoreGame/annotated.html
can also refer to that when one is confused.

**Pull request merged**
